### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by KivyDesign** [gottadiveintopython/kivymd-icon-viewer#1]
I found an error when scrolling, a really cozy and excellent application, and very useful. Thanks

 Traceback (most recent call last):
   File "main.py", line 50, in <module>
     IconViewerApp().run()
   File "/home/javier/anaconda3/lib/python3.7/site-packages/kivy/app.py", line 950, in run
     runTouchApp()
   File "/home/javier/anaconda3/lib/python3.7/site-packages/kivy/base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "/home/javier/anaconda3/lib/python3.7/site-packages/kivy/base.py", line 347, in mainloop
     self.idle()
   File "/home/javier/anaconda3/lib/python3.7/site-packages/kivy/base.py", line 391, in idle
     self.dispatch_input()
   File "/home/javier/anaconda3/lib/python3.7/site-packages/kivy/base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/javier/anaconda3/lib/python3.7/site-packages/kivy/base.py", line 301, in post_dispatch_input
     wid.dispatch('on_touch_move', me)
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/home/javier/anaconda3/lib/python3.7/site-packages/kivy/uix/scrollview.py", line 855, in on_touch_move
     if self.dispatch('on_scroll_move', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/home/javier/anaconda3/lib/python3.7/site-packages/kivy/uix/scrollview.py", line 908, in on_scroll_move
     self.effect_x.update(touch.x)
   File "/home/javier/anaconda3/lib/python3.7/site-packages/kivy/effects/scroll.py", line 116, in update
     self.displacement += abs(val - self.history[-1][1])
 IndexError: list index out of range

**Comment by gottadiveintopython** [comment]
I assume you are using Kivy 2.0.0. That version looks like having multiple bugs in ScrollView, which probably makes this app unstable. Currently, the best workaround is to use Kivy 1.9.1, which is the version when I made the app. And the second best would be to use the master branch.
